twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        project_title: CRM
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
